import DiplomaApi from '../../api/diplonma/DiplomaApi'

export default {
  namespaced: true,
  state: {
    diplomas: [],
    total: 0,
    indigenous: [
      { id: 1, name: 'Kinh (Việt)' },
      { id: 2, name: 'Tày' },
      { id: 3, name: 'Thái' },
      { id: 4, name: 'Mường' },
      { id: 5, name: 'Khmer' },
      { id: 6, name: 'Hoa' },
      { id: 7, name: 'Nùng' },
      { id: 8, name: 'Mông' },
      { id: 9, name: 'Dao' },
      { id: 10, name: 'Gia Rai' },
      { id: 11, name: 'Ê  Đê' },
      { id: 12, name: 'Ba Na' },
      { id: 13, name: 'Sán Chay' },
      { id: 14, name: 'Chăm' },
      { id: 15, name: 'Cơ Ho' },
      { id: 16, name: 'Xơ Đăng' },
      { id: 17, name: 'Sán Dìu' },
      { id: 18, name: 'Hrê' },
      { id: 19, name: 'RaGlay' },
      { id: 20, name: 'Mnông' },
      { id: 21, name: 'Thổ (4)' },
      { id: 22, name: 'Xtiêng' },
      { id: 23, name: 'Khơ mú' },
      { id: 24, name: 'Bru Vân Kiều' },
      { id: 25, name: 'Cơ Tu' },
      { id: 26, name: 'Giáy' },
      { id: 27, name: 'Tà Ôi' },
      { id: 28, name: 'Mạ' },
      { id: 29, name: 'Giẻ-Triêng' },
      { id: 30, name: 'Co' },
      { id: 31, name: 'Chơ Ro' },
      { id: 32, name: 'Xinh Mun' },
      { id: 33, name: 'Hà Nhì' },
      { id: 34, name: 'Chu Ru' },
      { id: 35, name: 'Lào' },
      { id: 36, name: 'La Chí' },
      { id: 37, name: 'Kháng' },
      { id: 38, name: 'Phù Lá' },
      { id: 39, name: 'La Hủ' },
      { id: 40, name: 'La Ha' },
      { id: 41, name: 'Pà Thẻn' },
      { id: 42, name: 'Lự' },
      { id: 43, name: 'Ngái' },
      { id: 44, name: 'Chứt' },
      { id: 45, name: 'Lô Lô' },
      { id: 46, name: 'Mảng' },
      { id: 47, name: 'Cơ Lao' },
      { id: 48, name: 'Bố Y' },
      { id: 49, name: 'Cống' },
      { id: 50, name: 'Si La' },
      { id: 51, name: 'Pu Péo' },
      { id: 52, name: 'Rơ Măm' },
      { id: 53, name: 'Brâu' },
      { id: 54, name: 'Ơ Đu' }
    ],
    nationality: [
      { id: 1, name: 'Afghanistan' },
      { id: 2, name: 'Åland Islands' },
      { id: 3, name: 'Albania' },
      { id: 4, name: 'Algérie (An-giê-ri)' },
      { id: 5, name: 'American Samoa' },
      { id: 6, name: 'Andorra (An-đô-ra)' },
      { id: 7, name: 'Angola (Ăng-gô-la)' },
      { id: 8, name: 'Anguilla' },
      { id: 9, name: 'Antarctica' },
      { id: 10, name: 'Antigua và Barbuda (An-ti-goa và Bác-bu-da)' },
      { id: 11, name: 'Argentina' },
      { id: 12, name: 'Armenia (Ác-mê-ni-a)' },
      { id: 13, name: 'Aruba' },
      { id: 14, name: 'Úc (Ốt-xrây-li-a)' },
      { id: 15, name: 'Áo' },
      { id: 16, name: 'Azerbaijan (A-giéc-bai-gian)' },
      { id: 17, name: 'Bahamas (Ba-ha-mát)' },
      { id: 18, name: 'Bahrain (Ba-ranh)' },
      { id: 19, name: 'Bangladesh (Băng-la-đét)' },
      { id: 20, name: 'Barbados (Bác-ba-đốt)' },
      { id: 21, name: 'Belarus (Bê-la-rút)' },
      { id: 22, name: 'Bỉ' },
      { id: 23, name: 'Belize (Bê-li-xê)' },
      { id: 24, name: 'Benin (Bê-nanh)' },
      { id: 25, name: 'Bermuda' },
      { id: 26, name: 'Bhutan (Bu-tan)' },
      { id: 27, name: 'Bolivia (Bô-li-vi-a)' },
      { id: 28, name: 'Bosna và Hercegovina (Bốt-xni-a và Héc-dê-gô-vi-na)' },
      { id: 29, name: 'Botswana' },
      { id: 30, name: 'Bouvet Island' },
      { id: 31, name: 'Brasil (Bra-xin)' },
      { id: 32, name: 'British Indian Ocean Territory' },
      { id: 33, name: 'Brunei (Bru-nây)' },
      { id: 34, name: 'Bulgaria (Bungari)' },
      { id: 35, name: 'Burkina Faso (Buốc-ki-na Pha-xô)' },
      { id: 36, name: 'Burundi' },
      { id: 37, name: 'Campuchia' },
      { id: 38, name: 'Cameroon (Ca-mơ-run)' },
      { id: 39, name: 'Canada (Ca-na-đa; Gia Nã Đại)' },
      { id: 40, name: 'Cabo Verde (Cáp Ve)' },
      { id: 41, name: 'Cayman Islands' },
      { id: 42, name: 'Trung Phi' },
      { id: 43, name: 'Tchad (Sát)' },
      { id: 44, name: 'Chile (Chi-lê)' },
      { id: 45, name: 'Trung Quốc' },
      { id: 46, name: 'Christmas Island' },
      { id: 47, name: 'Cocos (Keeling) Islands' },
      { id: 48, name: 'Colombia (Cô-lôm-bi-a)' },
      { id: 49, name: 'Comoros (Cô-mo)' },
      { id: 50, name: 'Cộng hòa Congo (Công-gô; Congo-Brazzaville)' },
      { id: 51, name: 'Cộng hòa Dân chủ Congo (Congo-Kinshasa)' },
      { id: 52, name: 'Cook Islands' },
      { id: 53, name: 'Costa Rica (Cốt-xta Ri-ca)' },
      { id: 54, name: 'Bờ Biển Ngà (Cốt-đi-voa)' },
      { id: 55, name: 'Croatia (Crô-a-ti-a)' },
      { id: 56, name: 'Cuba (Cu-ba)' },
      { id: 57, name: 'Síp' },
      { id: 58, name: 'Séc (Tiệp)' },
      { id: 59, name: 'Đan Mạch' },
      { id: 60, name: 'Djibouti (Gi-bu-ti)' },
      { id: 61, name: 'Dominica (Đô-mi-ni-ca)' },
      { id: 62, name: 'Cộng hòa Dominicana (Đô-mi-ni-ca-na)' },
      { id: 63, name: 'Ecuador (Ê-cu-a-đo)' },
      { id: 64, name: 'Ai Cập' },
      { id: 65, name: 'El Salvador (En Xan-va-đo)' },
      { id: 66, name: 'Guinea Xích Đạo (Ghi-nê Xích Đạo)' },
      { id: 67, name: 'Eritrea (Ê-ri-tơ-ri-a)' },
      { id: 68, name: 'Estonia (E-xtô-ni-a)' },
      { id: 69, name: 'Ethiopia (Ê-t(h)i-ô-pi-a)' },
      { id: 70, name: 'Falkland Islands (Malvinas)' },
      { id: 71, name: 'Faroe Islands' },
      { id: 72, name: 'Fiji (Phi-gi)' },
      { id: 73, name: 'Phần Lan' },
      { id: 74, name: 'Pháp (Pháp Lan Tây)' },
      { id: 75, name: 'French Guiana' },
      { id: 76, name: 'French Polynesia' },
      { id: 77, name: 'French Southern Territories' },
      { id: 78, name: 'Gabon (Ga-bông)' },
      { id: 79, name: 'Gambia (Găm-bi-a)' },
      { id: 80, name: 'Gruzia (Gru-di-a)' },
      { id: 81, name: 'Đức' },
      { id: 82, name: 'Ghana (Ga-na)' },
      { id: 83, name: 'Gibraltar' },
      { id: 84, name: 'Hy Lạp' },
      { id: 85, name: 'Greenland' },
      { id: 86, name: 'Grenada (Grê-na-đa)' },
      { id: 87, name: 'Guadeloupe' },
      { id: 88, name: 'Guam' },
      { id: 89, name: 'Guatemala (Goa-tê-ma-la)' },
      { id: 90, name: 'Guinea (Ghi-nê)' },
      { id: 91, name: 'Guinea-Bissau (Ghi-nê Bít-xao)' },
      { id: 92, name: 'Guyana (Gai-a-na)' },
      { id: 93, name: 'Haiti (Ha-i-ti)' },
      { id: 94, name: 'Heard Island And Mcdonald Islands' },
      { id: 95, name: 'Holy See (Vatican City State)' },
      { id: 96, name: 'Honduras (Hôn-đu-rát) (Ôn-đu-rát)' },
      { id: 97, name: 'Hong Kong' },
      { id: 98, name: 'Hungary (Hung-ga-ri)' },
      { id: 99, name: 'Iceland (Ai xơ len)' },
      { id: 100, name: 'Cộng hòa Ấn Độ' },
      { id: 101, name: 'Indonesia (In-đô-nê-xi-a)' },
      { id: 102, name: 'Iran' },
      { id: 103, name: 'Iraq (I-rắc)' },
      { id: 104, name: 'Ireland (Ai-len)' },
      { id: 105, name: 'Israel (I-xra-en)' },
      { id: 106, name: 'Ý (I-ta-li-a)' },
      { id: 107, name: 'Jamaica (Gia-mai-ca)' },
      { id: 108, name: 'Nhật Bản' },
      { id: 109, name: 'Jordan (Gioóc-đan-ni)' },
      { id: 110, name: 'Kazakhstan (Ca-dắc-xtan)' },
      { id: 111, name: 'Kenya (Kê-nhi-a)' },
      { id: 112, name: 'Kiribati' },
      { id: 113, name: 'Triều Tiên' },
      { id: 114, name: 'Hàn Quốc (Nam Hàn)' },
      { id: 115, name: 'Kuwait (Cô-oét)' },
      { id: 116, name: 'Kyrgyzstan (Cư-rơ-gư-xtan)' },
      { id: 117, name: 'Lào' },
      { id: 118, name: 'Latvia (Lat-vi-a)' },
      { id: 119, name: 'Li ban (Li-băng)' },
      { id: 120, name: 'Lesotho (Lê-xô-thô)' },
      { id: 121, name: 'Liberia (Li-bê-ri-a)' },
      { id: 122, name: 'Libya (Li-bi)' },
      { id: 123, name: 'Liechtenstein (Lích-ten-xtai)' },
      { id: 124, name: 'Litva (Lít-va)' },
      { id: 125, name: 'Luxembourg (Lúc-xem-bua)' },
      { id: 126, name: 'Macao' },
      { id: 127, name: 'Macedonia (Mã Cơ Đốn) (Ma-xê-đô-ni-a)' },
      { id: 128, name: 'Madagascar' },
      { id: 129, name: 'Malawi (Ma-la-uy)' },
      { id: 130, name: 'Malaysia (Mã Lai Tây Á)(Ma-lay-xi-a)' },
      { id: 131, name: 'Maldives (Man-di-vơ)' },
      { id: 132, name: 'Mali' },
      { id: 133, name: 'Malta (Man-ta)' },
      { id: 134, name: 'Quần đảo Marshall' },
      { id: 135, name: 'Martinique' },
      { id: 136, name: 'Mauritanie (Mô-ri-ta-ni)' },
      { id: 137, name: 'Mauritius (Mô-ri-xơ)' },
      { id: 138, name: 'Mayotte' },
      { id: 139, name: 'Mexico (Mê-hi-cô)' },
      { id: 140, name: 'Micronesia (Mi-crô-nê-di)' },
      { id: 141, name: 'Moldova (Môn-đô-va)' },
      { id: 142, name: 'Monaco (Mô-na-cô)' },
      { id: 143, name: 'Mông Cổ' },
      { id: 144, name: 'Montserrat' },
      { id: 145, name: 'Maroc' },
      { id: 146, name: 'Mozambique (Mô-dăm-bích)' },
      { id: 147, name: 'Myanma (Mi-an-ma)' },
      { id: 148, name: 'Namibia (Na-mi-bi-a)' },
      { id: 149, name: 'Nauru (Nau-ru)' },
      { id: 150, name: 'Nepal (Nê-pan)' },
      { id: 151, name: 'Hà Lan (Hòa Lan)' },
      { id: 152, name: 'Netherlands Antilles' },
      { id: 153, name: 'New Caledonia' },
      { id: 154, name: 'New Zealand (Niu Di-lân) (Tân Tây Lan)' },
      { id: 155, name: 'Nicaragua (Ni-ca-ra-goa)' },
      { id: 156, name: 'Niger (Ni-giê)' },
      { id: 157, name: 'Nigeria (Ni-giê-ri-a)' },
      { id: 158, name: 'Niue' },
      { id: 159, name: 'Norfolk Island' },
      { id: 160, name: 'Northern Mariana Islands' },
      { id: 161, name: 'Na Uy' },
      { id: 162, name: 'Oman (Ô-man)' },
      { id: 163, name: 'Pakistan (Pa-kít-xtan)' },
      { id: 164, name: 'Palau (Pa-lau)' },
      { id: 165, name: 'Palestinian Territory, Occupied' },
      { id: 166, name: 'Panama (Pa-na-ma)' },
      { id: 167, name: 'Papua New Guinea (Pa-pua Niu Ghi-nê)' },
      { id: 168, name: 'Paraguay (Pa-ra-goay)' },
      { id: 169, name: 'Peru (Pê-ru)' },
      { id: 170, name: 'Philippines (Phi-líp-pin)' },
      { id: 171, name: 'Pitcairn' },
      { id: 172, name: 'Ba Lan' },
      { id: 173, name: 'Bồ Đào Nha' },
      { id: 174, name: 'Puerto Rico' },
      { id: 175, name: 'Qatar (Ca-ta)' },
      { id: 176, name: 'Réunion' },
      { id: 177, name: 'Romania (Ru-ma-ni, Lỗ Ma Ni)' },
      { id: 178, name: 'Nga' },
      { id: 179, name: 'Rwanda (Ru-an-đa)' },
      { id: 180, name: 'Saint Helena' },
      { id: 181, name: 'Saint Kitts và Nevis (Xanh Kít và Nê-vít)' },
      { id: 182, name: 'Saint Lucia (San-ta Lu-xi-a)' },
      { id: 183, name: 'Saint Pierre And Miquelon' },
      { id: 184, name: 'Saint Vincent và Grenadines (Xanh Vin-xen và Grê-na-din)' },
      { id: 185, name: 'Samoa (Xa-moa)' },
      { id: 186, name: 'San Marino (San Ma-ri-nô)' },
      { id: 187, name: 'São Tomé và Príncipe (Sao Tô-mê và Prin-xi-pê)' },
      { id: 188, name: 'Ả Rập Saudi (Ả Rập Xê-út)' },
      { id: 189, name: 'Sénégal (Xê-nê-gan)' },
      { id: 190, name: 'Serbia (Xéc-bi-a)' },
      { id: 191, name: 'Seychelles (Xây-sen)' },
      { id: 192, name: 'Sierra Leone (Xi-ê-ra Lê-ôn)' },
      { id: 193, name: 'Singapore (Xinh-ga-po)' },
      { id: 194, name: 'Slovakia (Xlô-va-ki-a)' },
      { id: 195, name: 'Slovenia (Xlô-ven-ni-a)' },
      { id: 196, name: 'Solomon (Xô-lô-môn)' },
      { id: 197, name: 'Somalia (Xô-ma-li)' },
      { id: 198, name: 'Nam Phi' },
      { id: 199, name: 'South Georgia And The South Sandwich Islands' },
      { id: 200, name: 'Tây Ban Nha' },
      { id: 201, name: 'Sri Lanka (Xri Lan-ca)' },
      { id: 202, name: 'Sudan (Xu-đăng)' },
      { id: 203, name: 'Suriname (Xu-ri-nam)' },
      { id: 204, name: 'Svalbard And Jan Mayen' },
      { id: 205, name: 'Swaziland (Xoa-di-len)' },
      { id: 206, name: 'Thụy Điển' },
      { id: 207, name: 'Thụy Sĩ (Thụy Sỹ)' },
      { id: 208, name: 'Syria (Xi-ri)' },
      { id: 209, name: 'Taiwan, Province Of China' },
      { id: 210, name: 'Tajikistan (Tát-gi-kít-xtan)' },
      { id: 211, name: 'Tanzania (Tan-da-ni-a)' },
      { id: 212, name: 'Thái Lan' },
      { id: 213, name: 'Đông Timor (Ti-mo Lex-te)' },
      { id: 214, name: 'Togo (Tô-gô)' },
      { id: 215, name: 'Tokelau' },
      { id: 216, name: 'Tonga (Tông-ga)' },
      { id: 217, name: 'Trinidad và Tobago (Tri-ni-đát và Tô-ba-gô)' },
      { id: 218, name: 'Tunisia (Tuy-ni-di)' },
      { id: 219, name: 'Thổ Nhĩ Kỳ' },
      { id: 220, name: 'Turkmenistan (Tuốc-mê-ni-xtan)' },
      { id: 221, name: 'Turks And Caicos Islands' },
      { id: 222, name: 'Tuvalu' },
      { id: 223, name: 'Uganda (U-gan-đa)' },
      { id: 224, name: 'Ukraina (U-crai-na)' },
      { id: 225, name: 'Các Tiểu Vương quốc Ả Rập Thống nhất' },
      { id: 226, name: 'Vương quốc Liên hiệp Anh và Bắc Ireland' },
      { id: 227, name: 'Hoa Kỳ (Mỹ)' },
      { id: 228, name: 'United States Minor Outlying Islands' },
      { id: 229, name: 'Uruguay (U-ru-goay)' },
      { id: 230, name: 'Uzbekistan (U-dơ-bê-kít-xtan)' },
      { id: 231, name: 'Vanuatu (Va-nu-a-tu)' },
      { id: 232, name: 'Thành Vatican (Va-ti-căng)/Tòa Thánh' },
      { id: 233, name: 'Venezuela (Vê-nê-xu(y)-ê-la)' },
      { id: 234, name: 'Việt Nam' },
      { id: 235, name: 'Virgin Islands, British' },
      { id: 236, name: 'Virgin Islands, U.S.' },
      { id: 237, name: 'Wallis And Futuna' },
      { id: 238, name: 'Western Sahara' },
      { id: 239, name: 'Yemen (Y-ê-men)' },
      { id: 240, name: 'Zambia (Dăm-bi-a)' },
      { id: 241, name: 'Zimbabwe (Dim-ba-bu-ê)' },
      { id: 242, name: 'Cộng hòa Azerbaijan' },
      { id: 243, name: 'Cộng hòa Croatia' },
      { id: 244, name: 'Montenegro (Môn-tê-nê-grô)' },
      { id: 245, name: 'Nam Sudan' }
    ],
    rankings: [
      { id: 1, name: 'Xuất sắc' },
      { id: 2, name: 'Giỏi' },
      { id: 3, name: 'Khá' },
      { id: 4, name: 'Trung bình' },
      { id: 5, name: 'Yếu' },
      { id: 6, name: 'Kém' },
      { id: 7, name: 'Trung bình khá' }
    ],
    reqTypes: [
      { id: 1, name: 'Cấp mới' },
      { id: 2, name: 'Chỉnh sửa' },
      { id: 3, name: 'Huỷ bằng' }
    ],
    diplomaTypes: [
      { symbol: '5', name: 'Cao đẳng' },
      { symbol: '6', name: 'Cử nhân' },
      { symbol: '7', name: 'Thạc sĩ' },
      { symbol: '8', name: 'Tiến sĩ' },
      { symbol: 'C', name: 'Chứng chỉ Đào tạo liên tục (Bộ Y tế)' },
      { symbol: 'F', name: 'Chứng chỉ ngoại ngữ' },
      { symbol: 'F1', name: 'Chứng chỉ bồi dưỡng cán bộ ra đề thi ngoại ngữ' },
      { symbol: 'F2', name: 'Chứng chỉ bồi dưỡng cán bộ chấm thi nói và viết ngoại ngữ' },
      { symbol: 'I1', name: 'Chứng chỉ ứng dụng CNTT cơ bản' },
      { symbol: 'I2', name: 'Chứng chỉ ứng dụng CNTT nâng cao' }
    ],
    yearGraduations: []
  },
  getters: {
    getDiplomas: (state) => state.diplomas,
    getTotal: (state) => state.total,
    getIndigenous: (state) => state.indigenous,
    getNationality: (state) => state.nationality,
    getRankings: (state) => state.rankings,
    getReqTypes: (state) => state.reqTypes,
    getDiplomaTypes: (state) => state.diplomaTypes,
    getYearGraduations: (state) => state.yearGraduations
  },
  mutations: {
    SET_DIPLOMAS(state, data) {
      state.diplomas = [...data]
    },
    SET_TOTAL(state, data) {
      state.total = data
    },
    SET_YEAR_GRADUATES(state, data) {
      state.yearGraduations = [...data]
    }
  },
  actions: {
    async get_all_diplomas({ commit }, params) {
      const response = await DiplomaApi.getListDiplomas(params)
      try {
        commit('SET_DIPLOMAS', response.data)
        commit('SET_TOTAL', response.total)
      } catch (err) {
        this.loading = true
      }
    },

    async get_all_years_graduation({ commit }) {
      const res = await DiplomaApi.getListyear()
      try {
        commit('SET_YEAR_GRADUATES', ['All', ...res])
      } catch (err) {
        this.loading = true
      }
    }
  }
}
